CREATE TABLE IF NOT EXISTS game_action_records (
    commit_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    room_id BIGINT UNSIGNED NOT NULL,
    timeline_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    position BIGINT UNSIGNED NOT NULL,
    kind VARCHAR(24) NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    request_namespace VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_generation CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_revision BIGINT UNSIGNED NOT NULL,
    turn_before INT UNSIGNED NOT NULL,
    turn_after INT UNSIGNED NOT NULL,
    round_before INT UNSIGNED NOT NULL,
    round_after INT UNSIGNED NOT NULL,
    payload_version INT UNSIGNED NOT NULL,
    payload JSON NOT NULL,
    payload_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (commit_id),
    UNIQUE KEY uk_game_records_position (room_id, timeline_id, position),
    UNIQUE KEY uk_game_records_request (room_id, request_namespace, request_id),
    CONSTRAINT chk_game_record_kind CHECK (kind IN ('opening','action','skip_manual','skip_timeout','legacy_baseline')),
    CONSTRAINT chk_game_record_payload CHECK (JSON_TYPE(payload) = 'OBJECT'),
    CONSTRAINT chk_game_record_position CHECK ((kind = 'legacy_baseline' AND position = 0) OR (kind <> 'legacy_baseline' AND position > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS game_memory_operations (
    operation_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    room_id BIGINT UNSIGNED NOT NULL,
    kind VARCHAR(16) NOT NULL,
    fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_timeline_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_generation CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    target_timeline_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    target_save_id BIGINT UNSIGNED NULL,
    phase VARCHAR(16) NOT NULL,
    target_snapshot JSON NOT NULL,
    snapshot_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    next_retry_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    error_class VARCHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (operation_id),
    KEY idx_game_operations_retry (phase, next_retry_at, operation_id),
    KEY idx_game_operations_room (room_id, created_at),
    CONSTRAINT chk_game_operation_kind CHECK (kind IN ('start','load','end')),
    CONSTRAINT chk_game_operation_phase CHECK (phase IN ('prepared','redis_applied','completed','aborted','blocked')),
    CONSTRAINT chk_game_operation_snapshot CHECK (JSON_TYPE(target_snapshot) = 'OBJECT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
