CREATE TABLE IF NOT EXISTS game_summary_work (
  id CHAR(36) NOT NULL,
  room_id BIGINT UNSIGNED NOT NULL,
  timeline_id CHAR(36) NOT NULL,
  state_revision BIGINT UNSIGNED NOT NULL,
  expected_version BIGINT UNSIGNED NOT NULL,
  from_position BIGINT UNSIGNED NOT NULL,
  through_position BIGINT UNSIGNED NOT NULL,
  source_hash CHAR(64) NOT NULL,
  previous_summary TEXT NOT NULL,
  messages JSON NOT NULL,
  status VARCHAR(16) NOT NULL,
  owner_token CHAR(36) NOT NULL DEFAULT '',
  lease_until DATETIME(3) NOT NULL,
  next_retry_at DATETIME(3) NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  error_class VARCHAR(16) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_summary_version (timeline_id, expected_version),
  KEY idx_summary_due (status, next_retry_at, lease_until),
  KEY idx_summary_room (room_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
