package service

import "errors"

// 预定义业务错误，handler 层据此返回安全的用户提示
var (
	ErrUsernameAlreadyExists  = errors.New("username already exists")
	ErrEmailAlreadyExists     = errors.New("email already exists")
	ErrInvalidCredentials     = errors.New("invalid username or password")
	ErrInvalidRefreshToken    = errors.New("invalid refresh token")
	ErrUserNotFound           = errors.New("user not found")
	ErrScriptFileRequired     = errors.New("script PDF file is required")
	ErrScriptFileTooLarge     = errors.New("script PDF file is too large")
	ErrScriptFileExtension    = errors.New("script file must use the .pdf extension")
	ErrScriptFileContentType  = errors.New("script file must have application/pdf content type")
	ErrScriptFileSignature    = errors.New("script file has an invalid PDF signature")
	ErrScriptTitleTooLong     = errors.New("script title is too long")
	ErrScriptNotFound         = errors.New("script not found")
	ErrInvalidScriptStatus    = errors.New("invalid script parse status")
	ErrInvalidParseResult     = errors.New("invalid script parse result")
	ErrScriptStatusConflict   = errors.New("script status transition conflict")
	ErrInvalidGameRequest     = errors.New("invalid game request")
	ErrScriptNotReady         = errors.New("script is not ready")
	ErrCharacterNotFound      = errors.New("character not found in script")
	ErrAIUnavailable          = errors.New("AI service unavailable")
	ErrEmptyOpeningNarrative  = errors.New("AI returned an empty opening narrative")
	ErrGameStartConflict      = errors.New("game start status conflict")
	ErrInvalidActionEffects   = errors.New("invalid AI action effects")
	ErrInvalidGameAction      = errors.New("invalid game action")
	ErrGameRoomNotFound       = errors.New("game room not found")
	ErrGameRoomNotPlaying     = errors.New("game room is not playing")
	ErrGamePlayerNotFound     = errors.New("game player not found")
	ErrGameActionConflict     = errors.New("game action turn conflict")
	ErrActionRequestConflict  = errors.New("action request ID conflict")
	ErrInsufficientItems      = errors.New("insufficient item quantity")
	ErrEmptyActionNarrative   = errors.New("AI returned an empty action narrative")
	ErrGameRuntimeUnavailable = errors.New("game runtime unavailable")
	ErrInvalidGameSave        = errors.New("invalid game save request")
	ErrGameRoomNotSavable     = errors.New("game room cannot be saved")
	ErrInvalidPagination      = errors.New("invalid pagination parameters")
	ErrInternal               = errors.New("internal error")
)
